Add Solaris __gss_userok check

diff --git a/mod_gss/mod_gss/configure b/mod_gss/mod_gss/configure
--- a/mod_gss/mod_gss/configure
+++ b/mod_gss/mod_gss/configure
@@ -2767,13 +2767,86 @@ done
 if test "${enable_seam+set}" = set; then
   enableval="$enable_seam"
 
-    if test "x$enableval" != x"no" ; then
-       if test "x$enableval" != x"yes" ; then
-          SRC=$enableval
-       else
-          SRC="/usr/src/"
-       fi
-       CPPFLAGS="-I$SRC/uts/common/gssapi/mechs/krb5/include -I$SRC/lib/gss_mechs/mech_krb5/include"
+    if test "x$enableval" != "xno" ; then
+       echo "$as_me:$LINENO: checking for __gss_userok in -lgss" >&5
+echo $ECHO_N "checking for __gss_userok in -lgss... $ECHO_C" >&6
+if test "${ac_cv_lib_gss___gss_userok+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgss  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char __gss_userok ();
+int
+main ()
+{
+__gss_userok ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gss___gss_userok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gss___gss_userok=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gss___gss_userok" >&5
+echo "${ECHO_T}$ac_cv_lib_gss___gss_userok" >&6
+if test $ac_cv_lib_gss___gss_userok = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE___GSS_USEROK 1
+_ACEOF
+
+fi
+
+       if test "x$ac_cv_lib_gss___gss_userok" == "xno" ; then
+          if test "x$enableval" != "xyes" ; then
+             SRC=$enableval
+          else
+             SRC="/usr/src"
+          fi
+          CPPFLAGS="-I$SRC/uts/common/gssapi/mechs/krb5/include -I$SRC/lib/gss_mechs/mech_krb5/include"
 
 
 for ac_header in krb5.h com_err.h
@@ -2925,6 +2998,14 @@ fi
 
 done
 
+          if test "x$ac_cv_header_krb5_h" != "xno" ; then
+             echo " ## ------------------------------------------------------------------------------------------------------ ##"
+             echo " ## Add                                                                                                    ##"
+             echo " ## --with-includes=$SRC/uts/common/gssapi/mechs/krb5/include:$SRC/lib/gss_mechs/mech_krb5/include ##"
+             echo " ## to proftpd configure command                                                                           ##"
+             echo " ## ------------------------------------------------------------------------------------------------------ ##"
+          fi
+       fi
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SEAM_KERBEROS 1
