Some cofigure.in updates

diff --git a/mod_gss/mod_gss/configure.in b/mod_gss/mod_gss/configure.in
--- a/mod_gss/mod_gss/configure.in
+++ b/mod_gss/mod_gss/configure.in
@@ -41,12 +41,27 @@ esac
 enable_arg="no"
 check_mit() {
        AC_DEFINE(HAVE_INIT_CREDS_PASSWORD,1,[Define krb5_get_init_creds_password])
-       ac_gss_libs="-lgssapi_krb5 -ldes425 -lkrb5 -lk5crypto -lcom_err"
+       ac_gss_libs="-lgssapi_krb5 -ldes425 -lkrb5 -lk5crypto -lcom_err $LIBS"
        case $sys in
-	        Linux) ac_libdir=`rpm -q -l  krb5 | grep "libgssapi_krb5" |  sed -e 's/\/libgssapi_krb5.*//' | head -1`
-                       ac_includedir=`rpm -q -l krb5-devel | grep /krb5.h$ | sed -e 's/\/krb5.h//'`
+	        Linux) if test "x$enableval" != "xyes" ; then
+                         ac_libdir=$enableval/lib
+                         ac_includedir=$enableval/include
+                         if ! test -e $ac_libdir/libgssapi_krb5.a -a ! -e $ac_libdir/libgssapi_krb5.so ; then
+                           echo "configure: ##"
+                           echo "configure: ## Invalid lib directory $ac_libdir"
+                           echo "configure: ##"
+                         fi
+                         if ! test -e $ac_includedir/krb5.h ; then
+                           echo "configure: ##"
+                           echo "configure: ## Invalid include directory $ac_includedir"
+                           echo "configure: ##"
+                         fi
+                       else
+                         ac_libdir=`rpm -q -l  krb5 | grep "/libgssapi_krb5" |  sed -e 's/\/libgssapi_krb5.*//' | head -1`
+                         ac_includedir=`rpm -q -l krb5-devel | grep /krb5.h$ | sed -e 's/\/krb5.h//' | head -1`
+                       fi
                        if test "x$ac_includedir" != "x" ; then
-                          CPPFLAGS="$CPPFLAGS -I$ac_includedir"
+                         CPPFLAGS="$CPPFLAGS -I$ac_includedir"
                        fi
                        if test "x$ac_libdir" != "x" ; then
                          ac_gss_libs="-L$ac_libdir -Wl,-R$ac_libdir $ac_gss_libs"
@@ -59,10 +74,25 @@ check_mit() {
 check_heimdal(){
        AC_DEFINE(HAVE_HEIMDAL_KERBEROS,1,[Define Heimdal Kerberos])
        AC_DEFINE(HAVE_INIT_CREDS_PASSWORD,1,[Define krb5_get_init_creds_password])
-       ac_gss_libs="-lgssapi -lkrb5 -lcom_err -lasn1 -lroken";
+       ac_gss_libs="-lgssapi -lkrb5 -lcom_err -lasn1 -lroken $LIBS";
        case $sys in
-                Linux) ac_libdir=`rpm -q -l  heimdal-devel | grep "libroken" |  sed -e 's/\/libroken.*//' | head -1`
-                       ac_includedir=`rpm -q -l heimdal-devel | grep /krb5.h$ | sed -e 's/\/krb5.h//'`
+	        Linux) if test "x$enableval" != "xyes" ; then
+                         ac_libdir=$enableval/lib
+                         ac_includedir=$enableval/include
+                         if ! test -e $ac_libdir/libroken.a -a ! -e $ac_libdir/libroken.so ; then
+                           echo "configure: ##"
+                           echo "configure: ## Invalid lib directory $ac_libdir"
+                           echo "configure: ##"
+                         fi
+                         if ! test -e $ac_includedir/krb5.h ; then
+                           echo "configure: ##"
+                           echo "configure: ## Invalid include directory $ac_includedir"
+                           echo "configure: ##"
+                         fi
+                       else
+                         ac_libdir=`rpm -q -l  heimdal-devel | grep "/libroken" |  sed -e 's/\/libroken.*//' | head -1`
+                         ac_includedir=`rpm -q -l heimdal-devel | grep /krb5.h$ | sed -e 's/\/krb5.h//' | head -1`
+                       fi
                        if test "x$ac_includedir" != "x" ; then
                           CPPFLAGS="$CPPFLAGS -I$ac_includedir"
                        fi
@@ -136,7 +166,7 @@ check_seam(){
 
 dnl Define MIT libraries
 AC_ARG_ENABLE(mit,
-  [  --enable-mit		  enable use of MIT package (default=yes) ],
+  [  --enable-mit[=DIR]	  enable use of MIT package (default=yes) ],
   [
     if test "x$enableval" != "xno" ; then
        check_mit
@@ -144,7 +174,7 @@ AC_ARG_ENABLE(mit,
 
 dnl Define Heimdal libraries
 AC_ARG_ENABLE(heimdal,
-  [  --enable-heimdal	  enable use of Heimdal package (default=no) ],
+  [  --enable-heimdal[=DIR]	  enable use of Heimdal package (default=no) ],
   [
     if test "x$enableval" != "xno" ; then
        check_heimdal
@@ -160,7 +190,7 @@ AC_ARG_ENABLE(nas,
 
 dnl Define SEAM libraries
 AC_ARG_ENABLE(seam,
-  [  --enable-seam[=src]	  enable use of SEAM(Solaris) package (default=no) ],
+  [  --enable-seam[=SRC]	  enable use of SEAM(Solaris) package (default=no) ],
   [
     if test "x$enableval" != "xno" ; then
        check_seam
